### ISSUE TITLE
Task runner throws an error

### ISSUE THREAD

**Issue by visooof** [damienbod/AngularWebpackVisualStudio#78]
Task runner throws an error

Error: Implement me. Unknown stdin file type!
    at process.stdin (node.js:740:17)
    at ConsoleReporter.BaseReporter (C:\Program Files (x86)\Yarn\lib\reporters\base-reporter.js:64:39)
    at ConsoleReporter (C:\Program Files (x86)\Yarn\lib\reporters\console\console-reporter.js:54:21)
    at Object.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli\index.js:232:18)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
Process terminated with code 1.

**Comment by robisim74** [comment]
https://github.com/madskristensen/NpmTaskRunner/issues/46
