### ISSUE TITLE
Unhandled Promise rejection: Template parse errors:

### ISSUE THREAD

**Issue by gordingin** [damienbod/AngularWebpackVisualStudio#87]
I downloaded and successfully ran this version, nice job. I have have tried to incorporate a number of controls, all have failed to render (not compile) giving the following error.

Unhandled Promise rejection: Template parse errors:

I have tried 
https://github.com/ng2-ui/auto-complete
https://github.com/swimlane/ngx-datatable
https://github.com/ng2-ui/infinite-list

I am not sure if something is wrong since they all fail or I am doing something wrong. Could you please advised. 

Thanks
Ralph

Full Error:

Unhandled Promise rejection: Template parse errors:
Can't bind to 'source' since it isn't a known property of 'input'. ("<div class="container-fluid">

    <input auto-complete [(ngModel)]="myData" [ERROR ->][source]="mySource" />

    <h1>{{message}}</h1>
"): ng:///HomeModule/HomeComponent.html@2:46 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
Can't bind to 'source' since it isn't a known property of 'input'. ("<div class="container-fluid">

    <input auto-complete [(ngModel)]="myData" [ERROR ->][source]="mySource" />

    <h1>{{message}}</h1>
"): ng:///HomeModule/HomeComponent.html@2:46
    at syntaxError (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:24379:34) [<root>]
    at TemplateParser.webpackHotUpdate.257.TemplateParser.parse (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:34817:19) [<root>]
    at JitCompiler.webpackHotUpdate.257.JitCompiler._compileTemplate (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48589:39) [<root>]
    at http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48513:62 [<root>]
    at Set.forEach (native) [<root>]
    at JitCompiler.webpackHotUpdate.257.JitCompiler._compileComponents (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48513:19) [<root>]
    at createResult (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48398:19) [<root>]
    at Zone.run (http://localhost:8080/dist/polyfills.bundle.js:16831:43) [<root> => <root>]
    at http://localhost:8080/dist/polyfills.bundle.js:17466:57 [<root>]
    at Zone.runTask (http://localhost:8080/dist/polyfills.bundle.js:16871:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:8080/dist/polyfills.bundle.js:17299:35) [<root>] Error: Template parse errors:
Can't bind to 'source' since it isn't a known property of 'input'. ("<div class="container-fluid">

    <input auto-complete [(ngModel)]="myData" [ERROR ->][source]="mySource" />

    <h1>{{message}}</h1>
"): ng:///HomeModule/HomeComponent.html@2:46
    at syntaxError (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:24379:34) [<root>]
    at TemplateParser.webpackHotUpdate.257.TemplateParser.parse (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:34817:19) [<root>]
    at JitCompiler.webpackHotUpdate.257.JitCompiler._compileTemplate (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48589:39) [<root>]
    at http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48513:62 [<root>]
    at Set.forEach (native) [<root>]
    at JitCompiler.webpackHotUpdate.257.JitCompiler._compileComponents (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48513:19) [<root>]
    at createResult (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48398:19) [<root>]
    at Zone.run (http://localhost:8080/dist/polyfills.bundle.js:16831:43) [<root> => <root>]
    at http://localhost:8080/dist/polyfills.bundle.js:17466:57 [<root>]
    at Zone.runTask (http://localhost:8080/dist/polyfills.bundle.js:16871:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:8080/dist/polyfills.bundle.js:17299:35) [<root>]
consoleError @ zone.js:569
handleUnhandledRejection @ zone.js:574
_loop_1 @ zone.js:609
drainMicroTaskQueue @ zone.js:613
zone.js:571 Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'source' since it isn't a known property of 'input'. ("<div class="container-fluid">

    <input auto-complete [(ngModel)]="myData" [ERROR ->][source]="mySource" />

    <h1>{{message}}</h1>
"): ng:///HomeModule/HomeComponent.html@2:46
Error: Template parse errors:
Can't bind to 'source' since it isn't a known property of 'input'. ("<div class="container-fluid">

    <input auto-complete [(ngModel)]="myData" [ERROR ->][source]="mySource" />

    <h1>{{message}}</h1>
"): ng:///HomeModule/HomeComponent.html@2:46
    at syntaxError (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:24379:34) [<root>]
    at TemplateParser.webpackHotUpdate.257.TemplateParser.parse (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:34817:19) [<root>]
    at JitCompiler.webpackHotUpdate.257.JitCompiler._compileTemplate (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48589:39) [<root>]
    at http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48513:62 [<root>]
    at Set.forEach (native) [<root>]
    at JitCompiler.webpackHotUpdate.257.JitCompiler._compileComponents (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48513:19) [<root>]
    at createResult (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48398:19) [<root>]
    at Zone.run (http://localhost:8080/dist/polyfills.bundle.js:16831:43) [<root> => <root>]
    at http://localhost:8080/dist/polyfills.bundle.js:17466:57 [<root>]
    at Zone.runTask (http://localhost:8080/dist/polyfills.bundle.js:16871:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:8080/dist/polyfills.bundle.js:17299:35) [<root>]
    at syntaxError (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:24379:34) [<root>]
    at TemplateParser.webpackHotUpdate.257.TemplateParser.parse (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:34817:19) [<root>]
    at JitCompiler.webpackHotUpdate.257.JitCompiler._compileTemplate (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48589:39) [<root>]
    at http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48513:62 [<root>]
    at Set.forEach (native) [<root>]
    at JitCompiler.webpackHotUpdate.257.JitCompiler._compileComponents (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48513:19) [<root>]
    at createResult (http://localhost:8080/2.f008bb58cda8c6f73399.hot-update.js:48398:19) [<root>]
    at Zone.run (http://localhost:8080/dist/polyfills.bundle.js:16831:43) [<root> => <root>]
    at http://localhost:8080/dist/polyfills.bundle.js:17466:57 [<root>]
    at Zone.runTask (http://localhost:8080/dist/polyfills.bundle.js:16871:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:8080/dist/polyfills.bundle.js:17299:35) [<root>]
    at resolvePromise (http://localhost:8080/dist/polyfills.bundle.js:17418:31) [<root>]
    at resolvePromise (http://localhost:8080/dist/polyfills.bundle.js:17389:17) [<root>]
    at http://localhost:8080/dist/polyfills.bundle.js:17466:17 [<root>]
    at Zone.runTask (http://localhost:8080/dist/polyfills.bundle.js:16871:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:8080/dist/polyfills.bundle.js:17299:35) [<root>]
consoleError @ zone.js:571
handleUnhandledRejection @ zone.js:574
_loop_1 @ zone.js:609
drainMicroTaskQueue @ zone.js:613

**Comment by FabianGosebrink** [comment]
Does this problem still exist?
